-- Plant events / annotation layer.
-- Apply via Supabase SQL editor or CLI after 005.
--
-- Events are logged in the moment (or shortly after) so sensor traces can be
-- interpreted against interventions. occurred_at is user-settable and distinct
-- from created_at because events are routinely entered after the fact.
--
-- crop_type_at_event / lifecycle_stage_at_event mirror sensor_readings
-- provenance: stamp from the device's current profile at insert.

create table plant_events (
  id uuid primary key default gen_random_uuid(),
  device_id uuid not null references devices(id),
  occurred_at timestamptz not null,
  created_at timestamptz not null default now(),
  event_type text not null,
  quantity numeric null,
  quantity_unit text null,
  note text null,
  source text not null default 'manual',
  crop_type_at_event text null,
  lifecycle_stage_at_event text null
);

create index plant_events_device_occurred_at_idx
  on plant_events (device_id, occurred_at desc);

comment on table plant_events is
  'Manual and system annotations (irrigation, maintenance, stage changes, etc.) for interpreting sensor traces.';

comment on column plant_events.occurred_at is
  'When the event happened (user-settable, UTC). Distinct from created_at so late entries remain honest.';

comment on column plant_events.source is
  'manual = typed by a user; system = generated by the app (e.g. stage_change on profile update).';

comment on column plant_events.crop_type_at_event is
  'Crop profile key in effect when this event was logged. Nullable only if insert skips stamping.';

comment on column plant_events.lifecycle_stage_at_event is
  'Lifecycle stage in effect when this event was logged.';

-- Match sibling Dirt Signal tables: RLS on, no anon policies.
-- Sidecar uses the service role key, which bypasses RLS.
alter table plant_events enable row level security;
